# Generated by Django 4.1.5 on 2023-01-09 22:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_birthday_profile_city_profile_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="whatsapp",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
