# Generated by Django 4.1.5 on 2023-01-12 14:40

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_hidden_alter_profile_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "300x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=image_cropping.fields.ImageCropField(
                default="default.jpg", upload_to="profile_pics", verbose_name="Фото"
            ),
        ),
    ]
