# Generated by Django 4.1.5 on 2023-01-20 10:30

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_cropping_avatar_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=image_cropping.fields.ImageCropField(
                default="default.jpg",
                upload_to="profile_pics",
                verbose_name="Исходное фото",
            ),
        ),
    ]
