# Generated by Django 4.1.5 on 2023-01-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="background",
            field=models.ImageField(
                blank=True, upload_to="backgrounds/", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="tags",
            name="background",
            field=models.ImageField(
                blank=True, upload_to="backgrounds/", verbose_name="Фото"
            ),
        ),
    ]
