# Generated by Django 4.1.5 on 2023-01-11 08:46

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_cropping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "background",
                "1950x687",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="cropping",
            ),
        ),
    ]
