# Generated by Django 4.1.5 on 2023-01-11 14:08

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_category_image_remove_tags_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cropping_thumb",
            field=image_cropping.fields.ImageRatioField(
                "photo",
                "400x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="Обрезанное фото для каталога",
            ),
        ),
    ]
