# Generated by Django 4.1.5 on 2023-01-11 14:11

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_cropping_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cropping_thumb",
            field=image_cropping.fields.ImageRatioField(
                "photo",
                "444x250",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="Обрезанное фото для каталога",
            ),
        ),
    ]
