# Generated by Django 4.1.5 on 2023-01-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_category_level_category_lft_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": [["parent", "title"]],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
