# Generated by Django 4.1.5 on 2023-01-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": [["parent", "title"]],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
