# Generated by Django 4.1.5 on 2023-01-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
