# Generated by Django 4.1.5 on 2023-01-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="important",
            field=models.BooleanField(default=False, verbose_name="Важная статья"),
        ),
    ]
