# Generated by Django 4.1.5 on 2023-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_post_important"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_post.jpeg",
                upload_to="photo/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
    ]
