# Generated by Django 4.1.5 on 2023-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_home_icon_home_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
