# Generated by Django 4.1.5 on 2023-04-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0013_city_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255, verbose_name="Запрос")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата сбора"),
                ),
                (
                    "collect_status",
                    models.CharField(max_length=100, verbose_name="Статус"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collect_data",
                        to="cities.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор данных",
                "verbose_name_plural": "Сбор данных",
                "ordering": ["-date"],
            },
        ),
    ]
