# Generated by Django 4.1.5 on 2023-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectdata",
            name="url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Ссылка на Google maps"
            ),
        ),
    ]
