# Generated by Django 4.1.5 on 2023-01-13 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import mugla_site.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0004_city_cropping_alter_city_photo_alter_city_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photo/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "photo",
                        "1950x687",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Обрезанное фото для фона",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Пост")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                ("site", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Полезная заметка"
                    ),
                ),
                (
                    "cropping_thumb",
                    image_cropping.fields.ImageRatioField(
                        "photo",
                        "400x300",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Обрезанное фото для каталога",
                    ),
                ),
                (
                    "russian_speak",
                    models.BooleanField(
                        default=False, verbose_name="Есть русскоговорящий персонал"
                    ),
                ),
                (
                    "english_speak",
                    models.BooleanField(
                        default=False, verbose_name="Есть англоговорящий персонал"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="companies",
                        to="cities.city",
                        verbose_name="Города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["-created_at"],
            },
            bases=(mugla_site.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photo/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "photo",
                        "1950x687",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Обрезанное фото для фона",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Тег")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["title"],
            },
            bases=(mugla_site.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photo/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "photo",
                        "1950x687",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Обрезанное фото для фона",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Тип организации"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="companies.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип организации",
                "verbose_name_plural": "Типы",
                "ordering": ["title"],
            },
            bases=(mugla_site.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="comany_gellery/%Y/%m/%d/")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                to="companies.companytags",
                verbose_name="Теги",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="companies.type",
                verbose_name="Тип организации",
            ),
        ),
    ]
