# Generated by Django 4.1.5 on 2023-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_type_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companygallery",
            name="image",
            field=models.ImageField(upload_to="company_gallery/%Y/%m/%d/"),
        ),
    ]
