# Generated by Django 4.1.5 on 2023-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_alter_companygallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companygallery",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="company_gallery/%Y/%m/%d/",
                verbose_name="Доп. фото",
            ),
        ),
    ]
