# Generated by Django 4.1.5 on 2023-01-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0011_companytags_level_companytags_lft_companytags_parent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="companytags", name="level",),
        migrations.RemoveField(model_name="companytags", name="lft",),
        migrations.RemoveField(model_name="companytags", name="parent",),
        migrations.RemoveField(model_name="companytags", name="rght",),
        migrations.RemoveField(model_name="companytags", name="tree_id",),
    ]
