# Generated by Django 4.1.5 on 2023-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_remove_companytags_level_remove_companytags_lft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Компания"),
        ),
    ]
