# Generated by Django 4.1.5 on 2023-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_alter_company_photo_alter_companytags_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygallery",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
    ]
