# Generated by Django 4.1.5 on 2023-01-31 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0009_alter_city_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0015_companygallery_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Компания")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Полезная заметка"
                    ),
                ),
                (
                    "russian_speak",
                    models.BooleanField(
                        default=False, verbose_name="Есть русскоговорящий персонал"
                    ),
                ),
                (
                    "english_speak",
                    models.BooleanField(
                        default=False, verbose_name="Есть англоговорящий персонал"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="changes",
                        to="cities.city",
                        verbose_name="Города",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="companies.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="changes",
                        to="companies.companytags",
                        verbose_name="Теги",
                    ),
                ),
                (
                    "type",
                    mptt.fields.TreeForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="companies.type",
                        verbose_name="Тип организации",
                    ),
                ),
            ],
        ),
    ]
