# Generated by Django 4.1.5 on 2023-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_changecompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changecompany",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название компании"),
        ),
    ]
