# Generated by Django 4.1.5 on 2023-01-31 19:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_alter_changecompany_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changecompany",
            name="content",
            field=models.TextField(blank=True, verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="changecompany",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название компании"
            ),
        ),
        migrations.AlterField(
            model_name="changecompany",
            name="type",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes",
                to="companies.type",
                verbose_name="Тип организации",
            ),
        ),
    ]
