# Generated by Django 4.1.5 on 2023-02-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_company_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="address",),
    ]
