# Generated by Django 4.1.5 on 2023-02-01 21:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0020_remove_company_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Use map widget for point the house location",
                null=True,
                srid=4326,
            ),
        ),
    ]
