# Generated by Django 4.1.5 on 2023-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0023_company_address_company_open_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="google_link",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ссылка на компанию в Google"
            ),
        ),
    ]
