# Generated by Django 4.1.5 on 2023-01-05 20:01

from django.db import migrations, models
import mugla_site.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Город")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("telegram", models.URLField(verbose_name="Telegram")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ["title"],
            },
            bases=(mugla_site.utils.CustomStr, models.Model),
        ),
    ]
