# Generated by Django 4.1.5 on 2023-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="telegram",
            field=models.URLField(blank=True, verbose_name="Telegram"),
        ),
    ]
