# Generated by Django 4.1.5 on 2023-01-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_alter_city_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="backgrounds/", verbose_name="Фото"
            ),
        ),
    ]
