# Generated by Django 4.1.5 on 2023-01-11 14:18

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0003_alter_city_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "photo",
                "1950x687",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="Обрезанное фото для фона",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="photo/%Y/%m/%d/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
    ]
