# Generated by Django 4.1.5 on 2023-01-23 23:13

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0006_city_content_photo_city_cropping_content_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="cropping_content_photo",
            field=image_cropping.fields.ImageRatioField(
                "content_photo",
                "400x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="Обрезанное фото в контенте",
            ),
        ),
    ]
