# Generated by Django 4.1.5 on 2023-02-03 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0009_alter_city_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Use map widget for point the house location",
                null=True,
                srid=4326,
            ),
        ),
    ]
