# Generated by Django 4.1.5 on 2023-02-17 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import image_cropping.fields
import mugla_site.utils


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0010_city_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default_post.jpeg",
                        upload_to="photo/%Y/%m/%d/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "photo",
                        "1950x687",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Обрезанное фото для фона",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название региона"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Use map widget for point the house location",
                        null=True,
                        srid=4326,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=(mugla_site.utils.CustomStr, models.Model),
        ),
    ]
