# Generated by Django 4.1.5 on 2023-02-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0011_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region", old_name="description", new_name="content",
        ),
    ]
