# Generated by Django 4.1.5 on 2023-02-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0012_rename_description_region_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities.region",
                verbose_name="Регион",
            ),
            preserve_default=False,
        ),
    ]
