# Generated by Django 4.1.5 on 2023-02-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmessage",
            name="email",
            field=models.EmailField(
                default="q@q.ru", max_length=254, verbose_name="e-mail"
            ),
            preserve_default=False,
        ),
    ]
